### ISSUE TITLE
[TJPI] Meses com dados com uma linha

### ISSUE THREAD

**Issue by danielfireman** [dadosjusbr/coletor-cnj#12]
Alguns órgãos que disponibilizam suas planilhas no CNJ, **NÃO** colocam todos os valores corretamente, ficando com apenas o total de todos os valores.
  - Imagem de planilha com os valores corretos:
    > TJPI 09/2018 veja ela [**aqui**](https://paineis.cnj.jus.br/QvAJAXZfc/opendoc.htm?document=qvw_l%2FPainelCNJ.qvw&host=QVS%40neodimio03&anonymous=true&sheet=shPORT63Relatorios)

    ![image](https://user-images.githubusercontent.com/76446913/140088847-0a70b55f-99c7-4fb3-9ff7-ed0d0e5db523.png)
  - Imagem de uma das planilhas descritas acima:
    > TJPI 09/2020, veja ela [**aqui**](https://paineis.cnj.jus.br/QvAJAXZfc/opendoc.htm?document=qvw_l%2FPainelCNJ.qvw&host=QVS%40neodimio03&anonymous=true&sheet=shPORT63Relatorios)
  
    ![image](https://user-images.githubusercontent.com/76446913/140086513-9d0dbd02-7569-4fb5-b4e3-8e608641974b.png)

@marcos-inja poderia listar quais meses estão assim?

@nazareno iremos caminhar colocando esses dados no repo, seguindo a linha de não devemos tentar interpretar os dados.

**Comment by marcos-inja** [comment]
## Lista de meses com dados de uma linha
- Os campos marcados com **"X"** são os que tem planilhas com apenas uma linha.
- Os Campos marcados com **"-"** estão corretos, com planilhas com o nome do pessoal.
- Os que estão com **"Sem dados"**, é para os meses que não tem nenhuma planilha, para 2021, ainda falta adicionar essas planilhas.
 
|Meses|2018|2019|2020|2021|
|---------|------|-------|-------|-------|
|Janeiro|-|-|X|-|
|Fevereiro|-|-|X|-|
|Março|-|-|X|-|
|Abril|-|X|X|-|
|Maio|-|X|X|-|
|Junho|-|X|X|-|
|Julho|-|X|X|-|
|Agosto|-|X|X|-|
|Setembro|-|X|X|-|
|Outubro|-|X|X|-|
|Novembro|-|X|X|Sem dados|
|Dezembro|-|X|Sem dados|Sem dados|

**Comment by danielfireman** [comment]
Excelente! Obrigado, @marcos-inja!
