### ISSUE TITLE
Ler tempo de espera download de uma variável de ambiente

### ISSUE THREAD

**Issue by ghost** [dadosjusbr/coletor-cnj#8]
https://github.com/dadosjusbr/coletor-cnj-cdp/blob/main/crawler.go#L18

Quando a variável não estiver setada, o valor atual deve permanecer.

Isso permitirá acomodar mais facilmente internet lentas e etc

**Comment by danielfireman** [comment]
Corrigido por

https://github.com/dadosjusbr/coletor-cnj/commit/3415eb95a423df5ceabbcd51de3787d85c085f48

Adicionou as variáveis de ambiente:

`TIME_BETWEEN_STEPS`
`GENERAL_TIMEOUT`
`DOWNLOAD_TIMEOUT`
